<main>
    <div class="background-home"></div>
    <section class="container">
        <article class="slogan-container">
            <div class="slogan-box">
                <h2 class="slogan">Equipez-vous pour la victoire ! </h2>
            </div>
            <img class="svg-image" src="../img/svg.png" alt="tache orange ">
            <button>
                <a href="/products">Voir tous les produits</a>
                <i class="fa-solid fa-arrow-right" style="color: #ffffff;"></i></button>
        </article>
        <article>
            <h3>Meilleures ventes</h3>
            <div class="best-sells">
                <div class="card">
                    <img src="../img/chaussures-orange-2.jpg" alt="Photo chaussures de Tennis oranges">
                    <div class="price">
                        <p>Sneakers </p>
                        <p>39,99€</p>
                    </div>
                    <a class="button-see-more" href="/productDescription/3">
                        Voir plus
                    </a>
                </div>
                <div class="card">
                    <img src="../img/tshirt-homme.jpg" alt="Photo Tshirt homme bleu">
                    <div class="price">
                        <p>T-Shirt Homme</p>
                        <p>25,99€</p>
                    </div>
                    <a class="button-see-more" href="/productDescription/2">
                        Voir plus
                    </a>
                </div>
                <div class="card">
                    <img src="../img/tshirt_blanc_homme_produit.jpg" alt="Photo Tshirt homme blanc">
                    <div class="price">
                        <p>T-shirt Homme</p>
                        <p>25,99€</p>
                    </div>
                    <a class="button-see-more" href="/productDescription/11">
                        Voir plus
                    </a>
                </div>
            </div>
        </article>
    </section>

</main>