<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="../img/favicon-logo.png">
    <link rel="stylesheet" href="../public/css/style.css">
    <link rel="stylesheet" href="../public/css/form.css">
    <link rel="stylesheet" href="../public/css/products.css">
    <link rel="stylesheet" href="../public/css/account.css">
    <link rel="stylesheet" href="../public/css/basket.css">
    <link rel="stylesheet" href="../public/css/productDetails.css">
    <script src="https://kit.fontawesome.com/03938f57a2.js" crossorigin="anonymous"></script>
    <title>Ace Pro Tennis</title>
</head>


<body>
    <header>
        <div class="header-title">
            <img class="logo" src="../img/logo-tennis-removebg-preview.png" alt="logo tennis">
            <h1>Ace Pro Tennis !</h1>
        </div>
        <nav>
            <ul>
                <a href="/home">Accueil</a>
                <a href="/products">Produits</a>
                <a href="/contact">Contact</a>
                <?php if (isset($_SESSION['user'])) : ?>
                    <a href="/logout">Déconnexion</a>
                    <a href="/account">Compte</a>
                <?php else : ?>
                    <a href="/register">Inscription</a>
                    <a href="/login">Connexion</a>
                <?php endif; ?>

                <a href="/basket" id="cart-link"><i class="fa-solid fa-cart-shopping" style="color: #ffffff;"><span><?php echo isset($_SESSION['panier']) ? count($_SESSION['panier']) : 0; ?></span></i></a>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container">
            <div class="notif">
                <?php if (isset($_SESSION['success']) || isset($_SESSION['error'])) : ?>
                    <p class="alert alert-<?= isset($_SESSION['success']) ? 'success' : 'danger' ?>">
                        <?= $_SESSION['success'] ?? $_SESSION['error'] ?>
                    </p>
                    <?php unset($_SESSION['success'], $_SESSION['error']) ?>
                <?php endif; ?>
            </div>
            <?php if (isset($content)) : ?>
                <?= $content ?>
            <?php else : ?>
                <h2>Homepage Default</h2>
            <?php endif; ?>
        </div>

    </main>
    <footer>
        <div class="footer">
            <div class="row">
                <div class="link">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="link">
                    <h3>A Propos</h3>
                    <ul>
                        <li><a href="#">Entreprise</a></li>
                        <li><a href="#">Equipe</a></li>
                        <li><a href="#">Carrières</a></li>
                    </ul>
                </div>
            </div>
            <div class="company-footer">
                <h4>Ace Pro Tennis</h4>
                <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>

                <p class="copyright">Ace pro Tennis © 2023</p>
            </div>
        </div>
    </footer>
    <script src="public/js/FormValidator.js"></script>
    <script src="public/js/button.js"></script>
    <script src="public/js/filterProduct.js"></script>
</body>

</html>