<main>
    <div class="background-home"></div>
    <section class="container">
        <article class="menu-articles">
            <a href="#">Vêtements</a>
            <a href="#">Chaussures</a>
            <a href="#">Raquettes</a>
        </article>
        <article>
            <h2>Meilleures ventes</h2>
            <div class="best-sells">
                <div class="card">
                    <img src="../img/chaussures-orange-2.jpg" alt="Photo chaussures de Tennis oranges">
                    <div class="price">
                        <p>Sneakers </p>
                        <p>39,99€</p>
                    </div>
                </div>
                <div class="card">
                    <img src="../img/tshirt-homme.jpg" alt="Photo Tshirt homme bleu">
                    <div class="price">
                        <p>T-Shirt </p>
                        <p>25,99€</p>
                    </div>
                </div>
                <div class="card">
                    <img src="../img/raquette-verte.jpg" alt="Photo raquette de tennis verte">
                    <div class="price">
                        <p>Raquette</p>
                        <p>65,00€</p>
                    </div>
                </div>
            </div>
        </article>
    </section>

</main>