<div class="container-products">
    <nav class="menu-choice">
        <div><label for="order">Trier par:</label>
            <select name="order" id="order" onchange="filterProducts(this.value)">
                <option value="">--Choisissez une option--</option>
                <option value="price-ascendent">Du moins cher au plus cher</option>
                <option value="price-descendent">Du plus cher au moins cher</option>
            </select>
        </div>

        <div class="menu-checkbox">
            <div class="checkbox-racket-tennis checkbox">
                <input type="checkbox" id="all" name="option" value="all" onclick="uncheckAllExcept(this)">
                <label for="all">Tous les produits</label>
            </div>
            <div class="checkbox-racket-tennis checkbox">
                <input type="checkbox" id="racket" name="option" value="racket" onclick="uncheckAllExcept(this)">
                <label for="racket">Raquettes</label>
            </div>
            <div class="checkbox-shoes-men checkbox">
                <input type="checkbox" id="shoes-men" name="option" value="shoes-men" onclick="uncheckAllExcept(this)">
                <label for="shoes-men">Chaussures Hommes</label>
            </div>
            <div class="checkbox-shoes-women checkbox">
                <input type="checkbox" id="shoes-women" name="option" value="shoes-women" onclick="uncheckAllExcept(this)">
                <label for="shoes-women">Chaussures Femmes</label>
            </div>
            <div class="checkbox-shoes-women checkbox">
                <input type="checkbox" id="clothes" name="option" value="clothes" onclick="uncheckAllExcept(this)">
                <label for="clothes">Vêtements </label>
            </div>
        </div>
    </nav>
    <section>
        <article class="all-article">
            <div class="card-article all racket product" data-price="60,99">
                <div class="img-article">
                    <img src="../img/raquette-orange.jpg" alt="Photo d'une raquette orange'">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>Raquette Orange </p>
                        <p>60,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all clothes product" data-price="25,99">
                <div class="img-article ">
                    <img src="../img/tshirt-homme-product.jpg" alt="Photo d'un t-shirt bleu Homme">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>T-shirt Homme</p>
                        <p>25,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all shoes-men product" data-price="39,99">
                <div class="img-article ">
                    <img src="../img/chaussures-orange-product.jpg" alt="Photo de chaussures oranges Homme">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>Sneakers Oranges Homme</p>
                        <p>39,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all racket product" data-price="45,50">
                <div class="img-article ">
                    <img src="../img/raquette-bleu-product.jpg" alt="Photo d'une raquette bleue ">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>Raquette Bleue</p>
                        <p>45,50€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all shoes-women product" data-price="35,50">
                <div class="img-article">
                    <img src="../img/chaussures-blanche-product.jpg" alt="Photo de chaussures blanches">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>Sneakers Blanches Femme</p>
                        <p>35,50€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all shoes-women product" data-price="55,99">
                <div class="img-article ">
                    <img src="../img/chaussures-grise-product.jpg" alt="Photo de chaussures grises">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>Sneakers Grises Femme</p>
                        <p>55,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all clothes product" data-price="25,99">
                <div class="img-article ">
                    <img src="../img/tshirt-bleu-femme-3-product.jpg" alt="Photo d'un tshirt bleu Femme">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>T-shirt Bleu Femme</p>
                        <p>25,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all clothes product" data-price="25,99">
                <div class="img-article ">
                    <img src="../img/tshirt-orange-homme-2-product.jpg" alt="Photo d'un tshirt orange Homme">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>T-shirt Orange Homme</p>
                        <p>25,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all racket product" data-price="55,50">
                <div class="img-article ">
                    <img src="../img/raquette_rouge.jpg" alt="Photo d'une raquette rouge">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>Raquette rouge</p>
                        <p>55,50€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all clothes product" data-price="20,99">
                <div class="img-article ">
                    <img src="../img/tshirt_blanc_femme_produit.jpg" alt="Photo d'un tshirt blanc Femme">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>T-shirt Blanc Femme</p>
                        <p>20,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
            <div class="card-article all clothes product" data-price="20,99">
                <div class="img-article ">
                    <img src="../img/tshirt_blanc_homme_produit.jpg" alt="Photo d'un tshirt blanc Homme">
                </div>
                <div class="card-article-bottom">
                    <div class="card-article-price">
                        <p>T-shirt Blanc Homme</p>
                        <p>20,99€</p>
                    </div>
                    <button class="addtocart">
                        <div class="pretext">
                            <i class="fas fa-cart-plus"></i> Ajouter au panier
                        </div>
                        <div class="pretext done">
                            <div class="posttext"><i class="fas fa-check"></i> Ajouté !</div>
                        </div>
                    </button>
                </div>
            </div>
        </article>
    </section>
</div>